name: manage-azure-policy-f06351fb
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Vulnerabilities_in_security_configuration_on_your_virtual_machine_scale_sets_should_be_remediated_3c735d8a-a4ba-4a3a-b7cf-db7754cf57f4/**'
#      - 'policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Shutdown_b4a4d1eb-0263-441b-84cb-a44073d8372d/**'
#      - 'policies/Vulnerabilities_in_security_configuration_on_your_machines_should_be_remediated_e1e5fd5d-3e4c-4ce1-8661-7d1873ae6b15/**'
#      - 'policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Interactive_Logon_d472d2c9-d6a3-4500-9f5f-b15f123005aa/**'
#      - .github/workflows/manage-azure-policy-f06351fb.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f06351fb}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Vulnerabilities_in_security_configuration_on_your_virtual_machine_scale_sets_should_be_remediated_3c735d8a-a4ba-4a3a-b7cf-db7754cf57f4/**
          policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Shutdown_b4a4d1eb-0263-441b-84cb-a44073d8372d/**
          policies/Vulnerabilities_in_security_configuration_on_your_machines_should_be_remediated_e1e5fd5d-3e4c-4ce1-8661-7d1873ae6b15/**
          policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Interactive_Logon_d472d2c9-d6a3-4500-9f5f-b15f123005aa/**
